language: python
python:
  - 2.7
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script: 
  - make docs
after_success:
  - scripts/deploy_gh_pages.sh
branches:
  only:
    - master
