version: 2
jobs:
  st2docs:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: make docs
  ewcdocs:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: make bwcdocs
workflows:
  version: 2
  docs_checks:
    jobs:
      - st2docs
      - ewcdocs
